### ISSUE TITLE
大佬，如何连接ssh谢谢

### ISSUE THREAD

**Issue by 890506676** [AkashiCoin/qinglong-railway#1]
大佬，我部署成功了（按照大佬的教程，直接部署成功），可以进入青龙面板，可以拉库等操作，但是如何使用ssh连接，然后进行文件的修改呢？我没有找到路径，大佬能否教教，谢谢。

**Comment by AkashiCoin** [comment]
啊这，ssh的话是另一个项目的[Railway-Ngrok](https://github.com/AkashiCoin/Railway-Ngrok)，这个项目只负责部署青龙加使用的，ssh并没有，或者你改一下Dockerfile也可以用ssh

**Comment by 890506676** [comment]
谢谢大佬这么快回复，我去部署一下ngrok。看看能否访问青龙的文件夹，

**Comment by AkashiCoin** [comment]
>

**Comment by 890506676** [comment]
大佬，我部署了ngrok，相当于现在有两个project了，但是，我ssh连接以后，无法显示qinglong这个容器里面的文件啊。这两个project给的域名也不同。我现在就是想如何ssh进去青龙的文件夹，进行某些文件的编辑。

**Comment by AkashiCoin** [comment]
> 



> 大佬，我部署了ngrok，相当于现在有两个project了，但是，我ssh连接以后，无法显示qinglong这个容器里面的文件啊。这两个project给的域名也不同。我现在就是想如何ssh进去青龙的文件夹，进行某些文件的编辑。

要想ssh进去只有两个方法，
一、自己改这个项目的Dockerfile把ngrok的加进去。
二、使用ngrok的项目ssh进去部署青龙。

**Comment by 890506676** [comment]
好的，我试试去做第一个方法。
第二个方法，我之前试验过，但是出现各种各样的问题，(⊙﹏⊙)，
